# Generated by Django 4.2.22 on 2025-10-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MgnregaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_year', models.CharField(blank=True, max_length=10, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state_name', models.CharField(blank=True, max_length=50, null=True)),
                ('district_code', models.CharField(blank=True, max_length=10, null=True)),
                ('district_name', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_labour_budget', models.FloatField(blank=True, null=True)),
                ('average_wage_rate', models.FloatField(blank=True, null=True)),
                ('average_days_employment', models.FloatField(blank=True, null=True)),
                ('differently_abled_persons_worked', models.IntegerField(blank=True, null=True)),
                ('material_and_skilled_wages', models.FloatField(blank=True, null=True)),
                ('completed_works', models.IntegerField(blank=True, null=True)),
                ('gps_with_nil_exp', models.IntegerField(blank=True, null=True)),
                ('ongoing_works', models.IntegerField(blank=True, null=True)),
                ('central_liability_persondays', models.FloatField(blank=True, null=True)),
                ('sc_persondays', models.FloatField(blank=True, null=True)),
                ('sc_workers_percent', models.FloatField(blank=True, null=True)),
                ('st_persondays', models.FloatField(blank=True, null=True)),
                ('st_workers_percent', models.FloatField(blank=True, null=True)),
                ('total_admin_expenditure', models.FloatField(blank=True, null=True)),
                ('total_expenditure', models.FloatField(blank=True, null=True)),
                ('total_households_worked', models.IntegerField(blank=True, null=True)),
                ('total_individuals_worked', models.IntegerField(blank=True, null=True)),
                ('active_jobcards', models.IntegerField(blank=True, null=True)),
                ('active_workers', models.IntegerField(blank=True, null=True)),
                ('households_100_days', models.IntegerField(blank=True, null=True)),
                ('jobcards_issued', models.IntegerField(blank=True, null=True)),
                ('total_workers', models.IntegerField(blank=True, null=True)),
                ('total_works_takenup', models.IntegerField(blank=True, null=True)),
                ('wages', models.FloatField(blank=True, null=True)),
                ('women_persondays', models.FloatField(blank=True, null=True)),
                ('percent_category_b_works', models.FloatField(blank=True, null=True)),
                ('percent_agriculture_expenditure', models.FloatField(blank=True, null=True)),
                ('percent_nrm_expenditure', models.FloatField(blank=True, null=True)),
                ('percent_payments_within_15_days', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
